
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amans
 */
public class ReturnCancel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public ReturnCancel() {
        initComponents();
        setLocationRelativeTo(null);
        ProceedButton.setEnabled(false);
        clearAndLoadTable(RCTable,"C:\\Users\\amans\\Documents\\code\\java project data\\details.csv");    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   public void clearAndLoadTable(JTable table, String filename) {
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0); // Remove all rows
    try {
        BufferedReader reader = new BufferedReader(new FileReader(filename));
        String line;
        while ((line = reader.readLine()) != null) {
            String[] rowData = line.split(",");
            model.addRow(rowData);
        }
        reader.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
            ProceedButton.setEnabled(false);
            ProceedButton.setBackground(new Color(255, 255, 255));
            
}
   
   public int findRowByValue(JTable table, String columnName, Object value) {
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    int rowCount = model.getRowCount();
    int column = model.findColumn(columnName);
    for (int i = 0; i < rowCount; i++) {
        if (model.getValueAt(i, column).equals(value)) {
            return i;
        }
    }
    return -1; // Return -1 if the row is not found
}
   
   private void deleteRowFromCSV(String csvFilePath, JTable table) {
    int selectedRow = table.getSelectedRow();
    String selectedValue = table.getValueAt(selectedRow, 0).toString(); // get the value of the first column in the selected row

    try {
        File inputFile = new File(csvFilePath);
        File tempFile = new File("temp.csv");

        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));

        String currentLine;
        while ((currentLine = reader.readLine()) != null) {
            String[] row = currentLine.split(",");
            if (!row[0].equals(selectedValue)) {
                writer.write(currentLine + System.getProperty("line.separator"));
            }
        }
        writer.close();
        reader.close();
        inputFile.delete();
        tempFile.renameTo(inputFile);
    } catch (IOException e) {
        e.printStackTrace();
    }
            JOptionPane.showMessageDialog(null, "ThankYou");
}


   
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        showall = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RCTable = new javax.swing.JTable();
        ProceedButton = new javax.swing.JButton();
        ConfirmButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setForeground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search car by car id : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 209, 27));
        jPanel2.add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 178, -1));

        jLabel1.setBackground(new java.awt.Color(102, 255, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RETURN / CANCEL BOOKING");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 14, 365, 49));

        jButton3.setBackground(new java.awt.Color(102, 0, 102));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\amans\\Downloads\\Car-Rental-Systemadd\\src\\main\\java\\images\\93634 (5).png")); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 63, 63));

        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 125, 48));

        showall.setText("SHOW ALL");
        showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallActionPerformed(evt);
            }
        });
        jPanel2.add(showall, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 125, 48));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1011, 130));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("CAR DETAILS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 187, 149, -1));

        RCTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RCTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MAKER", "NAME", "CUSTOMER ID", "CUSTOMER NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RCTable.setGridColor(new java.awt.Color(0, 0, 0));
        RCTable.setRowHeight(45);
        RCTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        RCTable.setShowGrid(true);
        jScrollPane1.setViewportView(RCTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, 1036, 268));

        ProceedButton.setText("PROCEED");
        ProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ProceedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 125, 48));

        ConfirmButton1.setText("CONFIRM");
        ConfirmButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 125, 48));

        jMenu1.setText("FILE");

        jMenuItem2.setText("EXIT");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("CARS ");

        jMenuItem3.setText("ADD CAR");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("UPDATE CAR");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("REMOVE CAR");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("VIEW BOOKED CARS");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem1.setText("VIEW UNBOOKED CARS");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("CUSTOMER");

        jMenuItem7.setText("ADD CUSTOMER");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("UPDATE CUSTOMER");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("REMOVE CUSTOMER");
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("CAR OWNER");

        jMenuItem10.setText("ADD CAR OWNER");
        jMenu6.add(jMenuItem10);

        jMenuItem11.setText("UPDATE CAR OWNER");
        jMenu6.add(jMenuItem11);

        jMenuItem12.setText("REMOVE CAR OWNER");
        jMenu6.add(jMenuItem12);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("HELP");

        jMenuItem13.setText("CUSTOMER SUPPORT");
        jMenu7.add(jMenuItem13);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) RCTable.getModel();
        model.setRowCount(0);

        // Get the search string from the text field
        String searchText = searchtxt.getText().trim().toLowerCase();

        // Load data from the CSV file and add matching rows to the table
        try {
            BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\amans\\Documents\\code\\java project data\\details.csv"));
            String line;
            int k = 0;
            while ((line = reader.readLine()) != null) {
                String[] rowData = line.split(",");
                if (rowData[0].toLowerCase().equals(searchText)) {
                    model.addRow(rowData);
                    k=1;
                    
                }
                else if(searchtxt.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Enter a value");
                    k=2;
                    break;
                }

            }
                    if(k!=1 && k !=2){
                    JOptionPane.showMessageDialog(null, "No records found");
                }
            reader.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_searchActionPerformed

    private void ProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedButtonActionPerformed
        deleteRowFromCSV("C:\\Users\\amans\\Documents\\code\\java project data\\details.csv", RCTable);
        clearAndLoadTable(RCTable,"C:\\Users\\amans\\Documents\\code\\java project data\\details.csv");
        
    }//GEN-LAST:event_ProceedButtonActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Navigation n=new Navigation();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ConfirmButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButton1ActionPerformed
        // TODO add your handling code here:
             int selectedRow = RCTable.getSelectedRow();
             if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
             else{
             ProceedButton.setEnabled(true);
             ProceedButton.setBackground(new Color(0, 190, 0));
             }
    }//GEN-LAST:event_ConfirmButton1ActionPerformed

    private void showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallActionPerformed
        // TODO add your handling code here:
        clearAndLoadTable(RCTable,"C:\\Users\\amans\\Documents\\code\\java project data\\details.csv");
    }//GEN-LAST:event_showallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnCancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnCancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnCancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnCancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnCancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmButton1;
    private javax.swing.JButton ProceedButton;
    private javax.swing.JTable RCTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JButton showall;
    // End of variables declaration//GEN-END:variables
}
